// ============================================================
// Diff Reviewer — Task Parser
// Parse TaskBrief (goal + scope) from .orchestrator/current-task.md
// ============================================================

import type { TaskBrief } from '../context-composer/composer.js'

/**
 * Parse goal and scope from the markdown generated by composeAndPersist.
 * Extracts the ## Goal and ## Scope sections.
 */
export function parseCurrentTaskMd(content: string): TaskBrief {
  const lines = content.split('\n')

  let goal = ''
  let scope = ''
  let inGoal = false
  let inScope = false

  for (const line of lines) {
    if (line.startsWith('## Goal')) {
      inGoal = true
      inScope = false
      continue
    }
    if (line.startsWith('## Scope')) {
      inScope = true
      inGoal = false
      continue
    }
    if (line.startsWith('## ') || line.startsWith('---')) {
      inGoal = false
      inScope = false
      continue
    }
    const trimmed = line.trim()
    if (inGoal && trimmed && trimmed !== '(not specified)') {
      goal = goal ? goal + ' ' + trimmed : trimmed
    }
    if (inScope && trimmed && trimmed !== '(not specified)') {
      scope = scope ? scope + ' ' + trimmed : trimmed
    }
  }

  return {
    goal: goal || '(unknown goal)',
    scope: scope || '',
    constraints: [],
    open_questions: [],
    suggested_mode: 'safe',
  }
}
